name: Create release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true
                default: ''

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install NPM dependencies
              run: npm ci

            - name: Build dependencies
              run: npm run build

            - name: Prepare build repository
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "github-actions@github.com"
                  git checkout -b "release/${{ inputs.version }}"
                  git add -f build/*
                  git rm -r .github/
                  git rm .editorconfig
                  git rm .eslintignore
                  git rm .eslintrc.js
                  git rm .npmrc
                  git rm .nvmrc
                  git rm .prettierignore
                  git rm .prettierrc.js
                  git rm .stylelintignore
                  git rm .stylelintrc.js
                  git rm .wp-env.json
                  git rm package.json
                  git rm package-lock.json
                  git rm phpcs.xml.dist
                  git commit -m "Release ${{ inputs.version }}"
                  git tag "${{ inputs.version }}"
                  git push --tags

            - name: Create GitHub release
              id: create_github_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ inputs.version }}
                  release_name: ${{ inputs.version }}
                  body: ${{ steps.changelog.outputs.changes }}
                  draft: false
                  prerelease: false
